CREATE DATABASE QLSANPHAM
USE QLSANPHAM
USE MASTER

CREATE TABLE LOAISP(
MALOAI CHAR(5) PRIMARY KEY,
TENLOAI NVARCHAR(10)
)

CREATE TABLE SANPHAM(
MASP CHAR(5) PRIMARY KEY,
TENSP NVARCHAR(20),
MOTA NVARCHAR(50),
GIA BIGINT,
MALOAI CHAR(5) FOREIGN KEY (MALOAI) REFERENCES LOAISP(MALOAI)
)

CREATE TABLE KHACHHANG(
MAKH CHAR(5) PRIMARY KEY,
TENKH NVARCHAR(30),
DC NVARCHAR(100),
DT CHAR(11)
)

CREATE TABLE DONDH (
    SODDH CHAR(5) PRIMARY KEY,
    NGAYDAT DATE,
    MAKH CHAR(5) FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
)

CREATE TABLE CTDDH (
    SODDH CHAR(5),
    MASP CHAR(5),
    SOLUONG INT,
    PRIMARY KEY (SODDH, MASP),
    FOREIGN KEY (SODDH) REFERENCES DONDH(SODDH),
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
)

CREATE TABLE NGUYENLIEU (
    MANL CHAR(5) PRIMARY KEY,
    TENNL NVARCHAR(100),
    DVT NVARCHAR(10),
    GIA INT
)

CREATE TABLE LAM (
    MANL CHAR(5),
    MASP CHAR(5),
    SOLUONG FLOAT,
    PRIMARY KEY (MANL, MASP),
    FOREIGN KEY (MANL) REFERENCES NGUYENLIEU(MANL),
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
	)

INSERT INTO LOAISP(MALOAI, TENLOAI) VALUES
('L01',N'TỦ'),
('L02',N'BÀN'),
('L03',N'GIƯỜNG')

INSERT INTO SANPHAM(MASP,TENSP,MOTA,GIA,MALOAI) VALUES
('SP01',N'TỦ TRANG ĐIỂM', N'CAO 1.4M, RỘNG 2.2M', 1000000, 'L01'),
('SP02',N'GIƯỜNG ĐƠN CALI', N'RỘNG 1.4M', 1500000, 'L03'),
('SP03',N'TỦ DDA', N'CAO 1.6M, RỘNG 2.0M, CỬU KIẾNG', 800000, 'L01'),
('SP04',N'BÀN ĂN', N'1M x 1.5M', 650000, 'L02'),
('SP05',N'BÀN UỐNG TRÀ', N'TRÒN, 1.8M', 1100000, 'L02')

INSERT INTO KHACHHANG(MAKH,TENKH,DC,DT) VALUES
('KH001',N'TRẦN HẢI CƯỜNG', N'731 TRẦN HƯNG ĐẠO, Q.1, TP.HCM', '08-9776655'),
('KH002',N'NGUYỄN THỊ BÉ', N'638 NGUYỄN VĂN CỪ, Q.5, TP.HCM','0913-666123'),
('KH003',N'TRẦN THỊ MINH HOÀ', N'543 MAI THỊ LỰU, BA ĐÌNH, HÀ NỘI', '04-9238777'),
('KH004',N'PHẠM ĐÌNH TUÂN', N'975 LÊ LAI, P.3, TP VŨNG TÀU', '064-543678'),
('KH005',N'LÊ XUÂN HUYỆN',N'450 TRƯƠNG VƯƠNG,TP MỸ THO, TIỀN GIANG','073-987123'),
('KH006',N'VĂN HÙNG DŨNG',N'291 HỒ VĂN HUÊ, Q. PN, TP.HCM','08-8222111'),
('KH012',N'LÊ THỊ HƯƠNG HOA',N'980 LÊ HỒNG PHONG, TP. VŨNG TÀU','064-452100'),
('KH016',N'HÀ MINH TRÍ',N'332 NGUYỄN THÁI HỌC, TP. QUY NHƠN','056-565656')


INSERT INTO DONDH (SODDH,NGAYDAT,MAKH) VALUES
('DH001','2010-3-15','KH001'),
('DH002','2010-3-15','KH016'),
('DH003','2010-3-16','KH003'),
('DH004','2010-3-16','KH012'),
('DH005','2010-3-17','KH001'),
('DH006','2010-4-1','KH002')

INSERT INTO CTDDH(SODDH,MASP,SOLUONG) VALUES
('DH001','SP01',5),
('DH001','SP03',1),
('DH002','SP02',2),
('DH003','SP01',2),
('DH003','SP04',10),
('DH003','SP05',5),
('DH004','SP02',2),
('DH004','SP05',2),
('DH005','SP03',3),
('DH006','SP02',4),
('DH006','SP04',3),
('DH006','SP05',6)

INSERT INTO NGUYENLIEU(MANL,TENNL,DVT,GIA) VALUES
('NL01',N'GỖ LIM XP','m3',1200000),
('NL02',N'GỖ SAO NT','m3',1000000),
('NL03',N'GỖ TẠP NHAM','m3',500000),
('NL04',N'ĐINH LỚN','kg',40000),
('NL05',N'ĐINH NHỎ','kg',30000),
('NL06',N'KIẾNG','m2',350000)

INSERT INTO LAM(MANL,MASP,SOLUONG) VALUES
('NL01','SP01',1.2),
('NL03','SP01',0.3),
('NL06','SP01',2.5),
('NL02','SP02',1.1),
('NL04','SP02',2.2),
('NL02','SP03',0.9),
('NL05','SP03',2.1),
('NL02','SP04',1.3),
('NL04','SP04',1.7),
('NL03','SP05',0.8),
('NL05','SP05',0.5),
('NL06','SP05',2.4)


CREATE VIEW V1 AS
SELECT  TOP 1 WITH TIES TENLOAI,COUNT(*) AS SOLUONGSANPHAM
FROM SANPHAM S INNER JOIN LOAISP L ON S.MALOAI = L.MALOAI
GROUP BY TENLOAI
ORDER BY SOLUONGSANPHAM DESC

CREATE VIEW V2 AS
SELECT TENKH, DC
FROM KHACHHANG
WHERE MAKH NOT IN(
SELECT K.MAKH
FROM KHACHHANG K INNER JOIN DONDH D ON K.MAKH = D.MAKH
WHERE MONTH(NGAYDAT) = 3 AND YEAR(NGAYDAT) = 2010)

CREATE VIEW V3 AS
SELECT TOP 1 WITH TIES K.TENKH, DC, COUNT(D.SODDH) AS TONGSOHOADONDADAT
FROM KHACHHANG K INNER JOIN DONDH D ON K.MAKH = D.MAKH
WHERE MONTH(NGAYDAT) = 3 AND YEAR(NGAYDAT) = 2010
GROUP BY K.TENKH, DC
ORDER BY TONGSOHOADONDADAT DESC

CREATE VIEW V4 AS
SELECT TENSP,MOTA
FROM SANPHAM
WHERE MASP NOT IN (
SELECT S.MASP
FROM DONDH D INNER JOIN CTDDH C ON D.SODDH = C.SODDH
	INNER JOIN SANPHAM S ON S.MASP = C.MASP
WHERE MONTH(NGAYDAT) = 3 AND YEAR(NGAYDAT) = 2010)

CREATE VIEW V5 AS
SELECT TENKH,DC,SUM(SOLUONG) AS TONGTU
FROM DONDH D INNER JOIN CTDDH C ON D.SODDH = C.SODDH
	INNER JOIN SANPHAM S ON S.MASP = C.MASP
	INNER JOIN KHACHHANG K ON K.MAKH = D.MAKH
WHERE TENSP LIKE N'TỦ DDA'
GROUP BY TENKH,DC
HAVING SUM(SOLUONG) > 10

CREATE VIEW V6 AS
SELECT TOP 1 WITH TIES TENSP,S.GIA,LO.MALOAI, COUNT(MANL) AS SOLOAINGUYENLIEU
FROM SANPHAM S INNER JOIN LAM L ON L.MASP = S.MASP
			INNER JOIN LOAISP LO ON LO.MALOAI = S.MALOAI
GROUP BY TENSP,S.GIA,LO.MALOAI
ORDER BY COUNT(MANL) DESC

CREATE VIEW V7 AS
SELECT TENSP, SUM(L.SOLUONG * N.GIA) AS GIATHANHSX
FROM SANPHAM  S
INNER JOIN LAM L ON L.MASP = S.MASP
INNER JOIN NGUYENLIEU N ON N.MANL = L.MANL
GROUP BY TENSP
HAVING SUM(L.SOLUONG * N.GIA) > 1000000

CREATE VIEW V8 AS
SELECT TENSP, SUM(L.SOLUONG * N.GIA) AS GIATHANHSX,S.GIA,((S.GIA - SUM(L.SOLUONG * N.GIA)) / SUM(L.SOLUONG * N.GIA)) *100 AS PHANTRAMLAI
FROM SANPHAM  S
INNER JOIN LAM L ON L.MASP = S.MASP
INNER JOIN NGUYENLIEU N ON N.MANL = L.MANL
GROUP BY TENSP,S.GIA
HAVING ((S.GIA - SUM(L.SOLUONG * N.GIA)) / SUM(L.SOLUONG * N.GIA)) * 100 > 20

CREATE VIEW V9 AS
SELECT C.SODDH,NGAYDAT,SUM(S.GIA*SOLUONG) AS TONGTIEN
FROM CTDDH C INNER JOIN SANPHAM S ON C.MASP = S.MASP
INNER JOIN DONDH D ON D.SODDH = C.SODDH
GROUP BY C.SODDH,NGAYDAT
HAVING SUM(S.GIA*SOLUONG) > 100000000

CREATE VIEW V10 AS
SELECT N.TENNL, N.GIA
FROM NGUYENLIEU N
INNER JOIN LAM L ON N.MANL = L.MANL
INNER JOIN SANPHAM S ON S.MASP = L.MASP
GROUP BY N.TENNL, N.GIA
HAVING COUNT(DISTINCT S.MASP) = (SELECT COUNT(*) FROM SANPHAM)

CREATE VIEW V11 AS
SELECT K.TENKH, K.DC
FROM KHACHHANG K
INNER JOIN DONDH D ON K.MAKH = D.MAKH
INNER JOIN CTDDH C ON D.SODDH = C.SODDH
INNER JOIN SANPHAM S ON C.MASP = S.MASP
GROUP BY K.TENKH, K.DC
HAVING COUNT(DISTINCT S.MASP) = (SELECT COUNT(*) FROM SANPHAM)

CREATE VIEW V12 AS
SELECT S.TENSP, S.MOTA
FROM SANPHAM S
INNER JOIN CTDDH C ON S.MASP = C.MASP
INNER JOIN DONDH D ON C.SODDH = D.SODDH
GROUP BY S.TENSP, S.MOTA
HAVING COUNT(DISTINCT D.MAKH) = (SELECT COUNT(*) FROM KHACHHANG)

CREATE VIEW V13 AS
SELECT K.TENKH, K.DC, K.MAKH
FROM KHACHHANG K
WHERE NOT EXISTS (
    SELECT 1
    FROM DONDH D
    WHERE D.MAKH = K.MAKH
    AND D.NGAYDAT >= DATEADD(YEAR, -1, GETDATE())
)
SELECT K.TENKH, K.DC
FROM V13 K
ORDER BY K.MAKH

CREATE PROCEDURE P1
    @Ngay DATE
AS
BEGIN
    SELECT K.TENKH, K.DC
    FROM KHACHHANG K
    INNER JOIN DONDH D ON K.MAKH = D.MAKH
    WHERE D.NGAYDAT = @Ngay
END
EXEC P1'2010-3-15'

CREATE PROCEDURE P2
    @MASP CHAR(5)
AS
BEGIN
    SELECT K.TENKH, K.DC
    FROM KHACHHANG K
    INNER JOIN DONDH D ON K.MAKH = D.MAKH
    INNER JOIN CTDDH C ON D.SODDH = C.SODDH
    WHERE C.MASP = @MASP
END

EXEC P2 'SP01'

CREATE PROCEDURE P3
    @X BIGINT
AS
BEGIN
    SELECT K.TENKH, K.DC
    FROM KHACHHANG K
    INNER JOIN DONDH D ON K.MAKH = D.MAKH
    INNER JOIN CTDDH C ON D.SODDH = C.SODDH
    INNER JOIN SANPHAM S ON C.MASP = S.MASP
    GROUP BY K.TENKH, K.DC, D.SODDH
    HAVING SUM(S.GIA * C.SOLUONG) > @X
END
EXEC P3 @X = 10000000;

CREATE PROCEDURE P4
    @X BIGINT
AS
BEGIN
    SELECT K.TENKH, K.DC
    FROM KHACHHANG K
    INNER JOIN DONDH D ON K.MAKH = D.MAKH
    INNER JOIN CTDDH C ON D.SODDH = C.SODDH
    INNER JOIN SANPHAM S ON C.MASP = S.MASP
    GROUP BY K.TENKH, K.DC
    HAVING SUM(S.GIA * C.SOLUONG) > @X
END
EXEC P4 10000000


CREATE PROCEDURE P5
    @X BIGINT
AS
BEGIN
    SELECT S.TENSP, 
           SUM(L.SOLUONG * N.GIA) AS GIATHANHSX,
           S.GIA AS GIABAN, 
           (S.GIA - SUM(L.SOLUONG * N.GIA)) AS LAI
    FROM SANPHAM S
    INNER JOIN LAM L ON S.MASP = L.MASP
    INNER JOIN NGUYENLIEU N ON L.MANL = N.MANL
    GROUP BY S.TENSP, S.GIA
    HAVING (S.GIA - SUM(L.SOLUONG * N.GIA)) > @X
END

EXEC P5 100000

CREATE PROCEDURE P6
    @X INT
AS
BEGIN
    SELECT K.TENKH, K.DC
    FROM KHACHHANG K
    WHERE K.MAKH NOT IN (
        SELECT D.MAKH
        FROM DONDH D
        WHERE D.NGAYDAT >= DATEADD(DAY, -@X, GETDATE())
    )
END

EXEC P6 5463;

CREATE PROCEDURE P7
    @X INT 
AS
BEGIN
    SELECT S.TENSP, COUNT(DISTINCT C.SODDH) AS SODON
    FROM SANPHAM S
    INNER JOIN CTDDH C ON S.MASP = C.MASP
    GROUP BY S.TENSP
    HAVING COUNT(DISTINCT C.SODDH) > @X
END

EXEC P7 2

CREATE PROCEDURE P8
    @X INT
AS
BEGIN
    SELECT S.TENSP, SUM(C.SOLUONG) AS TONGSL
    FROM SANPHAM S
    INNER JOIN CTDDH C ON S.MASP = C.MASP
    GROUP BY S.TENSP
    HAVING SUM(C.SOLUONG) > @X
END

EXEC P8 10;

CREATE PROCEDURE P9
    @X BIGINT
AS
BEGIN
    SELECT S.TENSP, SUM(C.SOLUONG * S.GIA) AS TONGTIEN
    FROM SANPHAM S
    INNER JOIN CTDDH C ON S.MASP = C.MASP
    GROUP BY S.TENSP
    HAVING SUM(C.SOLUONG * S.GIA) > @X
END
EXEC P9 10000000

CREATE TRIGGER T1
ON DONDH
FOR INSERT
AS
BEGIN
    DECLARE @MAKH CHAR(5), @NGAYDAT DATE;
    SELECT @MAKH = MAKH, @NGAYDAT = NGAYDAT FROM INSERTED;
    IF (SELECT COUNT(*) FROM DONDH WHERE MAKH = @MAKH AND NGAYDAT = @NGAYDAT) > 2
    BEGIN
        PRINT('Khách hàng chỉ được đặt tối đa 2 đơn hàng mỗi ngày.');
        ROLLBACK
    END
END
INSERT INTO DONDH (SODDH,NGAYDAT,MAKH) VALUES
('DH008','2010-3-15','KH001')
INSERT INTO DONDH (SODDH,NGAYDAT,MAKH) VALUES
('DH009','2010-3-15','KH001')

CREATE TRIGGER T2
ON CTDDH
FOR INSERT
AS
BEGIN
    DECLARE @SODDH CHAR(5)
    DECLARE @TOTALQUANTITY INT
    SELECT @SODDH = SODDH FROM INSERTED
    SELECT @TOTALQUANTITY = SUM(SOLUONG) 
    FROM CTDDH
    WHERE SODDH = @SODDH
    IF @TOTALQUANTITY > 100
    BEGIN
        PRINT('Tổng số lượng sản phẩm trong đơn hàng không được vượt quá 100.')
        ROLLBACK
    END
END
INSERT INTO CTDDH(SODDH,MASP,SOLUONG) VALUES
('DH002','SP03',101)


CREATE TRIGGER T3
ON CTDDH
AFTER INSERT, UPDATE
AS
BEGIN
    DECLARE @MASP CHAR(5), @SOLUONG INT, @GIA_BAN BIGINT, @GIA_SX INT, @LAILOSS DECIMAL(5,2)
    IF (SELECT COUNT(*) FROM INSERTED) > 1
    BEGIN
        RAISERROR('Chỉ có thể chèn hoặc cập nhật một dòng tại một thời điểm', 16, 1)
        ROLLBACK
        RETURN
    END
    SELECT @MASP = MASP, @SOLUONG = SOLUONG FROM INSERTED
    SELECT @GIA_BAN = GIA FROM SANPHAM WHERE MASP = @MASP
    SELECT @GIA_SX = SUM(L.SOLUONG * N.GIA)
    FROM LAM L
    INNER JOIN NGUYENLIEU N ON L.MANL = N.MANL
    WHERE L.MASP = @MASP
    SET @LAILOSS = ((@GIA_BAN - @GIA_SX) / @GIA_SX) * 100
    IF @LAILOSS < 50
    BEGIN
        PRINT('Sản phẩm này bị lỗ hơn 50%%, không thể thêm hoặc cập nhật đơn hàng.')
        ROLLBACK
    END
END

INSERT INTO CTDDH (SODDH, MASP, SOLUONG)
VALUES ('DH001', 'SP02', 5)



CREATE PROCEDURE C1
    @X INT,
    @Y CHAR(5)
AS
BEGIN
    DECLARE @ProductCount INT = 1
    DECLARE @ProductName NVARCHAR(50);
    DECLARE @ProductDescription NVARCHAR(255)
    DECLARE @ProductPrice BIGINT
    DECLARE @CategoryName NVARCHAR(50)
    SELECT @CategoryName = TENLOAI FROM LOAISP WHERE MALOAI = @Y
    PRINT 'Tên loại: ' + @CategoryName
    DECLARE product_cursor CURSOR FOR
    SELECT TENSP, MOTA, GIA
    FROM SANPHAM
    WHERE MALOAI = @Y 
    ORDER BY GIA DESC
    OPEN product_cursor
    FETCH NEXT FROM product_cursor INTO @ProductName, @ProductDescription, @ProductPrice
    WHILE @@FETCH_STATUS = 0 AND @ProductCount <= @X
    BEGIN
        PRINT '• Sản phẩm ' + CAST(@ProductCount AS NVARCHAR(10)) + ': ' + @ProductName + ' - Mô tả: ' + @ProductDescription + ' - Giá: ' + CAST(@ProductPrice AS NVARCHAR(20))
        SET @ProductCount = @ProductCount + 1

        FETCH NEXT FROM product_cursor INTO @ProductName, @ProductDescription, @ProductPrice
    END

    CLOSE product_cursor
    DEALLOCATE product_cursor
END
EXEC C1 3, 'L02'

CREATE PROCEDURE C2
AS
BEGIN
    DECLARE @MASP CHAR(5)
    DECLARE @GIA BIGINT
    DECLARE @GiaSX BIGINT;
    DECLARE @NewPrice BIGINT
    DECLARE product_cursor CURSOR FOR
    SELECT MASP, GIA
    FROM SANPHAM
    OPEN product_cursor
    FETCH NEXT FROM product_cursor INTO @MASP, @GIA
    WHILE @@FETCH_STATUS = 0
    BEGIN
        SELECT @GiaSX = SUM(L.SOLUONG * N.GIA)
        FROM LAM L
        INNER JOIN NGUYENLIEU N ON L.MANL = N.MANL
        WHERE L.MASP = @MASP;
        IF ((@GIA - @GiaSX) / @GiaSX) > 0.30
        BEGIN
            SET @NewPrice = @GIA * 0.9
        END
        ELSE IF (@GIA < @GiaSX)
        BEGIN
            SET @NewPrice = @GiaSX
        END
        ELSE
        BEGIN
            SET @NewPrice = @GIA * 1.05
        END
        UPDATE SANPHAM
        SET GIA = @NewPrice
        WHERE MASP = @MASP
        FETCH NEXT FROM product_cursor INTO @MASP, @GIA
    END
    CLOSE product_cursor
    DEALLOCATE product_cursor
END

EXEC C2
SELECT *
FROM SANPHAM

CREATE PROCEDURE C3
    @Month INT
AS
BEGIN
    DECLARE @OrderDate DATE
    DECLARE @SODDH CHAR(5)
    DECLARE @MAKH CHAR(5)
    DECLARE @TotalAmount BIGINT
    DECLARE @RowNum INT
    DECLARE order_cursor CURSOR FOR
    SELECT DISTINCT CAST(NGAYDAT AS DATE)
    FROM DONDH
    WHERE MONTH(NGAYDAT) = @Month
    ORDER BY CAST(NGAYDAT AS DATE)
    OPEN order_cursor;
    FETCH NEXT FROM order_cursor INTO @OrderDate
    WHILE @@FETCH_STATUS = 0
    BEGIN
        PRINT 'Ngày ' + CONVERT(VARCHAR, DAY(@OrderDate)) + '/' + CONVERT(VARCHAR, @Month) + '/' + CONVERT(VARCHAR, YEAR(@OrderDate))
        SET @RowNum = 1
        DECLARE order_details_cursor CURSOR FOR
        SELECT D.SODDH, D.MAKH, SUM(C.SOLUONG * S.GIA) AS TotalAmount
        FROM DONDH D
        INNER JOIN CTDDH C ON D.SODDH = C.SODDH
        INNER JOIN SANPHAM S ON C.MASP = S.MASP
        WHERE MONTH(D.NGAYDAT) = @Month AND DAY(D.NGAYDAT) = DAY(@OrderDate)
        GROUP BY D.SODDH, D.MAKH
        ORDER BY TotalAmount DESC
        OPEN order_details_cursor
        FETCH NEXT FROM order_details_cursor INTO @SODDH, @MAKH, @TotalAmount
        WHILE @@FETCH_STATUS = 0
        BEGIN
            PRINT CAST(@RowNum AS VARCHAR) + '- ' + @SODDH + ': ' + @MAKH + ', Tổng tiền: ' + CONVERT(VARCHAR, @TotalAmount)
            SET @RowNum = @RowNum + 1
            FETCH NEXT FROM order_details_cursor INTO @SODDH, @MAKH, @TotalAmount;
        END
        CLOSE order_details_cursor
        DEALLOCATE order_details_cursor
        FETCH NEXT FROM order_cursor INTO @OrderDate
    END
    CLOSE order_cursor
    DEALLOCATE order_cursor
END
EXEC C3 3