DROP DATABASE QLBANHANG
USE master
CREATE DATABASE QLBANHANG
USE QLBANHANG
CREATE TABLE KHACHHANG (
	MAKH VARCHAR(5) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR(50),
	DT VARCHAR(11) CHECK(DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
							OR DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
							OR DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
							OR DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	EMAIL VARCHAR(30)
	)
CREATE TABLE VATTU (
	MAVT VARCHAR(5) NOT NULL PRIMARY KEY,
	TENVT NVARCHAR(30) NOT NULL,
	DVT NVARCHAR(20),
	GIAMUA MONEY CHECK(GIAMUA > 0),
	SLTON INT CHECK(SLTON >=0)
	)
CREATE TABLE HOADON (
	MAHD VARCHAR(10) NOT NULL PRIMARY KEY,
	NGAY DATE NOT NULL CHECK (NGAY < GETDATE()),
	MAKH VARCHAR(5) NOT NULL FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH),
	TONGTG FLOAT
	)
CREATE TABLE CTHD (
	MAHD VARCHAR(10) NOT NULL,
	MAVT VARCHAR(5) NOT NULL,
	SL INT CHECK (SL > 0),
	KHUYENMAI FLOAT,
	GIABAN FLOAT,
	PRIMARY KEY(MAHD,MAVT),
	FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
	FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT)
	)

SET DATEFORMAT DMY

INSERT INTO VATTU(MAVT,TENVT,DVT,GIAMUA,SLTON) VALUES ('VT01',N'Xi măng',N'Bao',50000,5000)
INSERT INTO VATTU(MAVT,TENVT,DVT,GIAMUA,SLTON) VALUES ('VT02',N'Cát',N'Khối',45000,50000)
INSERT INTO VATTU(MAVT,TENVT,DVT,GIAMUA,SLTON) VALUES ('VT03',N'Gạch ống',N'Viên',120,800000)
INSERT INTO VATTU(MAVT,TENVT,DVT,GIAMUA,SLTON) VALUES ('VT04',N'Gạch thẻ',N'Viên',110,800000)
INSERT INTO VATTU(MAVT,TENVT,DVT,GIAMUA,SLTON) VALUES ('VT05',N'Đá lớn',N'Khối',25000,100000)
INSERT INTO VATTU(MAVT,TENVT,DVT,GIAMUA,SLTON) VALUES ('VT06',N'Đá lớn',N'Khối',33000,100000)
INSERT INTO VATTU(MAVT,TENVT,DVT,GIAMUA,SLTON) VALUES ('VT07',N'Lam gió',N'Cái',15000,50000)

INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,DT,EMAIL) VALUES ('KH01',N'Nguyễn Thị Bé',N'Tân Bình','38457895','bnt@yahoo.com')
INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,DT,EMAIL) VALUES ('KH02',N'Lê Hoàng Nam',N'Bình Chánh','39878987','namlehoang@gmail.com')
INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,DT,EMAIL) VALUES ('KH03',N'Trần Thị Chiêu',N'Tân Bình','38457895',NULL)
INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,DT,EMAIL) VALUES ('KH04',N'Mai Thị Quế Anh',N'Bình Chánh',NULL,NULL)
INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,DT,EMAIL) VALUES ('KH05',N'Lê Văn Sáng',N'Quận 10',NULL,'sanglv@hcm.vnn.vn')
INSERT INTO KHACHHANG(MAKH,TENKH,DIACHI,DT,EMAIL) VALUES ('KH06',N'Trần Hoàng',N'Tân Bình','38457879',NULL)

INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD001','12/5/2010','KH01',NULL)
INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD002','25/5/2010','KH02',NULL)
INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD003','25/5/2010','KH01',NULL)
INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD004','25/5/2010','KH04',NULL)
INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD005','26/5/2010','KH04',NULL)
INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD006','2/6/2010','KH03',NULL)
INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD007','22/6/2010','KH04',NULL)
INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD008','25/6/2010','KH03',NULL)
INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD009','15/8/2010','KH04',NULL)
INSERT INTO HOADON(MAHD,NGAY,MAKH,TONGTG) VALUES ('HD010','30/9/2010','KH01',NULL)

INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD001','VT01',5,NULL,52000)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD001','VT05',10,NULL,30000)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD002','VT03',10000,NULL,150)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD003','VT02',20,NULL,55000)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD004','VT03',50000,NULL,150)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD004','VT04',20000,NULL,120)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD005','VT05',10,NULL,30000)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD005','VT06',15,NULL,35000)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD005','VT07',20,NULL,17000)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD006','VT04',10000,NULL,120)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD007','VT04',20000,NULL,125)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD008','VT01',100,NULL,55000)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD008','VT02',20,NULL,47000)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD009','VT02',25,NULL,48000)
INSERT INTO CTHD(MAHD,MAVT,SL,KHUYENMAI,GIABAN) VALUES ('HD010','VT01',25,NULL,57000)



CREATE VIEW V1 AS
SELECT *
FROM KHACHHANG
WHERE DIACHI LIKE N'%Tân Bình%'

SELECT *
FROM V1

CREATE VIEW V2 AS
SELECT MAKH,TENKH,DIACHI,EMAIL
FROM KHACHHANG
WHERE DT IS NULL

SELECT *
FROM V2

CREATE VIEW V3 AS
SELECT MAKH,TENKH,DIACHI
FROM KHACHHANG
WHERE DT IS NULL AND EMAIL IS NULL

SELECT *
FROM V3

CREATE VIEW V4 AS
SELECT MAKH,TENKH,DIACHI,DT,EMAIL
FROM KHACHHANG
WHERE DT IS NOT NULL AND EMAIL IS NOT NULL

SELECT *
FROM V4

CREATE VIEW V5 AS
SELECT MAVT, TENVT, GIAMUA
FROM VATTU
WHERE DVT LIKE N'Cái'

SELECT *
FROM V5

CREATE VIEW V6 AS
SELECT MAVT,TENVT,DVT,GIAMUA
FROM VATTU
WHERE GIAMUA > 25000

SELECT *
FROM V6

CREATE VIEW V7 AS
SELECT MAVT,TENVT,DVT,GIAMUA
FROM VATTU
WHERE TENVT LIKE N'%Gạch%'

SELECT *
FROM V7

CREATE VIEW V8 AS
SELECT MAVT, TENVT, DVT, GIAMUA
FROM VATTU
WHERE GIAMUA BETWEEN 20000 AND 40000

SELECT *
FROM V8

CREATE VIEW V9 AS
SELECT MAHD, NGAY,TENKH,DIACHI,DT
FROM HOADON H INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH

SELECT *
FROM V9

CREATE VIEW V10 AS
SELECT MAHD,TENKH,DIACHI,DT
FROM HOADON H INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
WHERE NGAY = '25/5/2010'

SELECT *
FROM V10

CREATE VIEW V11 AS
SELECT MAHD,NGAY,TENKH,DIACHI,DT
FROM HOADON H INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
WHERE YEAR(NGAY) = 2010 AND MONTH(NGAY) = 6

SELECT *
FROM V11

CREATE VIEW V12 AS
SELECT DISTINCT TENKH,DIACHI,DT
FROM HOADON H INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
WHERE YEAR(NGAY) = 2010 AND MONTH(NGAY) = 6

SELECT *
FROM V12

CREATE VIEW V13 AS
SELECT TENKH,DIACHI,DT
FROM KHACHHANG
WHERE MAKH NOT IN (SELECT MAKH
					FROM HOADON
					WHERE YEAR(NGAY) = 2010 AND MONTH(NGAY) = 6)
SELECT *
FROM V13

CREATE VIEW V14 AS
SELECT C.MAHD,C.MAVT,TENVT,DVT,GIABAN,GIAMUA,SL,(GIAMUA * SL) AS N'Trị giá mua',(GIABAN * SL) AS  N'Trị giá bán'
FROM VATTU V INNER JOIN CTHD C ON V.MAVT = C.MAVT
SELECT *
FROM V14

CREATE VIEW V15 AS
SELECT C.MAHD,C.MAVT,TENVT,DVT,GIABAN,GIAMUA,SL,(GIAMUA * SL) AS N'Trị giá mua',(GIABAN * SL) AS  N'Trị giá bán'
FROM VATTU V INNER JOIN CTHD C ON V.MAVT = C.MAVT
WHERE GIABAN >= GIAMUA
SELECT *
FROM V1

CREATE VIEW V16 AS
SELECT C.MAHD,C.MAVT,TENVT,DVT,GIABAN,GIAMUA,SL,(GIAMUA * SL) AS N'Trị giá mua',(GIABAN * SL) AS  N'Trị giá bán',
KHUYENMAI = (CASE WHEN SL > 100 THEN 0.1 ELSE NULL END)
FROM VATTU V INNER JOIN CTHD C ON V.MAVT = C.MAVT

SELECT *
FROM V16

CREATE VIEW V17 AS
SELECT *
FROM VATTU
WHERE MAVT NOT IN (SELECT MAVT
					FROM CTHD)
SELECT *
FROM V17

CREATE VIEW V18 AS
SELECT H.MAHD,NGAY,TENKH,DIACHI,DT,TENVT,DVT,GIAMUA,GIABAN,SL,(GIAMUA * SL) AS N'Trị giá mua',(GIABAN * SL) AS  N'Trị giá bán'
FROM KHACHHANG K INNER JOIN HOADON H ON K.MAKH = H.MAKH
				INNER JOIN CTHD C ON H.MAHD = C.MAHD
				INNER JOIN VATTU V ON C.MAVT = V.MAVT
SELECT *
FROM V18
CREATE VIEW V19 AS
SELECT H.MAHD,NGAY,TENKH,DIACHI,DT,TENVT,DVT,GIAMUA,GIABAN,SL,(GIAMUA * SL) AS N'Trị giá mua',(GIABAN * SL) AS  N'Trị giá bán'
FROM KHACHHANG K INNER JOIN HOADON H ON K.MAKH = H.MAKH
				INNER JOIN CTHD C ON H.MAHD = C.MAHD
				INNER JOIN VATTU V ON C.MAVT = V.MAVT
WHERE YEAR(NGAY) = 2010 AND MONTH(NGAY) = 5
SELECT *
FROM V19
CREATE VIEW V20 AS
SELECT H.MAHD,NGAY,TENKH,DIACHI,DT,TENVT,DVT,GIAMUA,GIABAN,SL,(GIAMUA * SL) AS N'Trị giá mua',(GIABAN * SL) AS  N'Trị giá bán'
FROM KHACHHANG K INNER JOIN HOADON H ON K.MAKH = H.MAKH
				INNER JOIN CTHD C ON H.MAHD = C.MAHD
				INNER JOIN VATTU V ON C.MAVT = V.MAVT
WHERE YEAR(NGAY) = 2010 AND MONTH(NGAY) BETWEEN 1 AND 5
SELECT *
FROM V20

CREATE VIEW V21 AS
SELECT C.MAHD,NGAY,TENKH,DIACHI,SUM(SL*GIABAN) AS N'Tổng trị giá từng hóa đơn'
FROM HOADON H INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
				INNER JOIN CTHD C ON H.MAHD = C.MAHD
GROUP BY C.MAHD,NGAY,TENKH,DIACHI
SELECT *
FROM V21
CREATE VIEW V22 AS
SELECT TOP 1 WITH TIES C.MAHD,NGAY,TENKH,DIACHI,SUM(SL*GIABAN) AS N'Tổng trị giá từng hóa đơn'
FROM HOADON H INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
				INNER JOIN CTHD C ON H.MAHD = C.MAHD
GROUP BY C.MAHD,NGAY,TENKH,DIACHI
ORDER BY SUM(SL*GIABAN) DESC
SELECT *
FROM V22

CREATE VIEW V23 AS
SELECT TOP 1 WITH TIES C.MAHD,NGAY,TENKH,DIACHI,SUM(SL*GIABAN) AS N'Tổng trị giá từng hóa đơn'
FROM HOADON H INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
				INNER JOIN CTHD C ON H.MAHD = C.MAHD
GROUP BY C.MAHD,NGAY,TENKH,DIACHI
HAVING YEAR(NGAY) = 2010 AND MONTH(NGAY) = 5
ORDER BY SUM(SL*GIABAN) DESC
SELECT *
FROM V23

CREATE VIEW V24 AS
SELECT MAKH,COUNT(MAHD) AS N'Số hóa đơn đã có'
FROM HOADON
GROUP BY MAKH
SELECT *
FROM V24

CREATE VIEW V25 AS
SELECT MAKH,MONTH(NGAY) AS N'Tháng',COUNT(MAHD) AS N'Số hóa đơn đã có'
FROM HOADON
GROUP BY MAKH,MONTH(NGAY)
SELECT *
FROM V25

CREATE VIEW V26 AS
SELECT TOP 1 WITH TIES COUNT(H.MAHD) AS N'Số hóa đơn',K.MAKH,TENKH,DIACHI,DT,EMAIL
FROM KHACHHANG K INNER JOIN HOADON H ON K.MAKH = H.MAKH
GROUP BY K.MAKH,TENKH,DIACHI,DT,EMAIL
ORDER BY COUNT(H.MAHD) DESC
SELECT *
FROM V26

CREATE VIEW V27 AS
SELECT TOP 1 WITH TIES SUM(SL) AS N'Số lượng hàng đã mua',K.MAKH,TENKH,DIACHI,DT,EMAIL
FROM HOADON H INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
				INNER JOIN CTHD C ON H.MAHD = C.MAHD
GROUP BY K.MAKH,TENKH,DIACHI,DT,EMAIL
ORDER BY SUM(SL) DESC
SELECT *
FROM V27
CREATE VI
EW V28 AS
SELECT TOP 1 WITH TIES COUNT(MAHD) AS N'Số lượng xuất hiện trong hóa đơn',V.MAVT,TENVT,DVT,GIAMUA
FROM CTHD C INNER JOIN VATTU V ON C.MAVT = V.MAVT
GROUP BY V.MAVT,TENVT,DVT,GIAMUA
ORDER BY COUNT(MAHD) DESC
SELECT *
FROM V28

CREATE VIEW V29 AS
SELECT TOP 1 WITH TIES SUM(SL) AS N'Số lượng',C.MAVT
FROM CTHD C INNER JOIN VATTU V ON C.MAVT = V.MAVT
GROUP BY C.MAVT
ORDER BY SUM(SL) DESC
SELECT *
FROM V29

CREATE VIEW V30 AS
SELECT K.MAKH,TENKH,DIACHI,CASE WHEN COUNT(MAHD) = 0 THEN NULL ELSE COUNT(MAHD) END AS N'Số lượng hóa đơn đã mua'
FROM KHACHHANG K LEFT JOIN HOADON H ON K.MAKH = H.MAKH
GROUP BY K.MAKH,TENKH,DIACHI
SELECT *
FROM V30

CREATE PROCEDURE P1 
@X DATETIME 
AS 
SELECT * 
FROM HOADON H INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
WHERE NGAY = @X

SET DATEFORMAT DMY
EXEC P1 '25/5/2010'

CREATE PROCEDURE P2
@X INT
AS
SELECT H.MAKH,TENKH,DIACHI,DT,EMAIL,SUM(SL*GIABAN) AS N'Tong tri gia'
FROM CTHD C INNER JOIN HOADON H ON C.MAHD = H.MAHD
			INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
GROUP BY H.MAKH,TENKH,DIACHI,DT,EMAIL
HAVING SUM(SL*GIABAN) > @X

EXEC P2 30000
--36026980
--2850
CREATE PROCEDURE P3
@X INT
AS
SELECT TOP (@X) WITH TIES H.MAKH,TENKH,DIACHI,DT,EMAIL,SUM(SL*GIABAN) AS N'Tong tri gia'
FROM CTHD C INNER JOIN HOADON H ON C.MAHD = H.MAHD
			INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
GROUP BY H.MAKH,TENKH,DIACHI,DT,EMAIL
ORDER BY SUM(SL*GIABAN)DESC

EXEC P3 3

CREATE PROCEDURE P4
@X INT
AS
SELECT TOP (@X) WITH TIES SUM(SL)AS N'Số lượng bán',C.MAVT,TENVT
FROM CTHD C INNER JOIN VATTU V ON C.MAVT = V.MAVT
GROUP BY C.MAVT,TENVT
ORDER BY SUM(SL) DESC

EXEC P4 3

CREATE PROCEDURE P5
@X INT
AS
SELECT TOP (@X) WITH TIES SUM((GIABAN - GIAMUA)*SL) AS N'Lãi',C.MAVT,TENVT
FROM CTHD C INNER JOIN VATTU V ON C.MAVT = V.MAVT
GROUP BY C.MAVT,TENVT
ORDER BY SUM((GIABAN - GIAMUA)*SL)

EXEC P5 5

CREATE PROCEDURE P6
@X INT
AS
SELECT TOP (@X) WITH TIES SUM(GIABAN*SL) AS N'Tổng trị giá',H.MAHD
FROM CTHD C INNER JOIN HOADON H ON C.MAHD = H.MAHD
GROUP BY H.MAHD
ORDER BY SUM(GIABAN*SL) DESC

EXEC P6 5

CREATE PROCEDURE P7
AS
UPDATE CTHD
SET KHUYENMAI = CASE WHEN SL > 500 THEN 0.1
					WHEN SL > 100 THEN 0.05
					ELSE NULL END
EXEC P7
SELECT *
FROM CTHD

CREATE PROCEDURE P8
AS
UPDATE VATTU
SET SLTON = SLTON - SL
FROM VATTU V INNER JOIN CTHD C ON V.MAVT = C.MAVT

EXEC P8
SELECT *
FROM VATTU
--!!!!!!

CREATE PROCEDURE P9
AS
UPDATE HOADON
SET TONGTG = TONGTRIGIATUNGHOADON
FROM HOADON H INNER JOIN CTHD C ON H.MAHD = C.MAHD
				INNER JOIN (SELECT MAHD,SUM(SL*GIABAN) AS TONGTRIGIATUNGHOADON
							FROM CTHD
							GROUP BY MAHD) T ON T.MAHD = C.MAHD
EXEC P9

SELECT *
FROM HOADON

CREATE TABLE KH_VIP (
	MAKHVIP VARCHAR(5) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR(50),
	DT VARCHAR(11) CHECK(DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
							OR DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
							OR DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'
							OR DT LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),
	EMAIL VARCHAR(30)
	FOREIGN KEY (MAKHVIP) REFERENCES KHACHHANG(MAKH)
	)

CREATE PROCEDURE P10
AS
INSERT INTO KH_VIP
SELECT K.MAKH,TENKH,DIACHI,DT,EMAIL
FROM CTHD C INNER JOIN HOADON H ON C.MAHD = H.MAHD
			INNER JOIN KHACHHANG K ON H.MAKH = K.MAKH
GROUP BY K.MAKH,TENKH,DIACHI,DT,EMAIL
HAVING SUM(SL*GIABAN)> 10000000
EXEC P10
DROP TABLE KH_VIP
SELECT *
FROM KH_VIP

CREATE FUNCTION F1(@NAM INT)
RETURNS FLOAT
AS
BEGIN
DECLARE @DOANHTHU FLOAT
SET @DOANHTHU = (SELECT SUM(SL*GIABAN)
					FROM CTHD C INNER JOIN HOADON H ON C.MAHD = H.MAHD
					WHERE YEAR(NGAY) = @NAM)
RETURN @DOANHTHU
END

SELECT dbo.F1(2011) AS DOANHTHU

CREATE FUNCTION F2(@THANG INT,@NAM INT)
RETURNS FLOAT
AS
BEGIN
DECLARE @DOANHTHU FLOAT
SET @DOANHTHU = (SELECT SUM(SL*GIABAN)
					FROM CTHD C INNER JOIN HOADON H ON C.MAHD = H.MAHD
					WHERE YEAR(NGAY) = @NAM AND MONTH(NGAY)=@THANG)
RETURN @DOANHTHU
END

SELECT dbo.F2(9,2010) AS DOANHTHU

CREATE FUNCTION F3(@MAKHACHHANG VARCHAR(5))
RETURNS FLOAT
AS
BEGIN
DECLARE @DOANHTHU FLOAT
SET @DOANHTHU = (SELECT SUM(SL*GIABAN)
					FROM CTHD C INNER JOIN HOADON H ON C.MAHD = H.MAHD
					WHERE MAKH = @MAKHACHHANG)
RETURN @DOANHTHU
END

SELECT dbo.F3('KH02') AS DOANHTHU

CREATE FUNCTION F4(@MAVATTU VARCHAR(5),@THANG INT,@NAM INT)
RETURNS INT
AS
BEGIN
DECLARE @SOLUONG INT
IF @THANG IS NULL
BEGIN
	SET @SOLUONG =(SELECT SUM(SL)
				FROM CTHD C INNER JOIN VATTU V ON C.MAVT = V.MAVT
				INNER JOIN HOADON H ON C.MAHD = H.MAHD
				WHERE C.MAVT = @MAVATTU AND YEAR(NGAY) = @NAM)
END
ELSE
BEGIN
	SET @SOLUONG =(SELECT SUM(SL)
				FROM CTHD C INNER JOIN VATTU V ON C.MAVT = V.MAVT
				INNER JOIN HOADON H ON C.MAHD = H.MAHD
				WHERE C.MAVT = @MAVATTU AND MONTH(NGAY) = @THANG AND YEAR(NGAY) = @NAM)
END
RETURN @SOLUONG
END
SELECT dbo.F4('VT07',NULL,2010) AS SOLUONG

CREATE FUNCTION F5(@MAMATHANG VARCHAR(5))
RETURNS FLOAT
AS
BEGIN
DECLARE @LAI FLOAT
IF @MAMATHANG IS NULL
BEGIN
	SET @LAI = (SELECT SUM((GIABAN-GIAMUA)*SL)
				FROM VATTU V INNER JOIN CTHD C ON V.MAVT = C.MAVT)
END
ELSE
BEGIN
	SET @LAI = (SELECT SUM((GIABAN-GIAMUA)*SL)
				FROM VATTU V INNER JOIN CTHD C ON V.MAVT = C.MAVT
				WHERE V.MAVT = @MAMATHANG)
END
	RETURN @LAI
END

SELECT dbo.F5(NULL) AS LAI