/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bt02_01;

import java.io.File;
import java.io.IOException;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class frmBT02_01 extends javax.swing.JFrame {

    /**
     * Creates new form frmBT02_01
     */
    public frmBT02_01() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcpath = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        btnPath = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtKytu = new javax.swing.JTextField();
        btnLietKe = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFile = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập đường dẫn:");

        btnPath.setText("Chọn đường dẫn");
        btnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPathActionPerformed(evt);
            }
        });

        jLabel2.setText("Loại bỏ các file không chứa ký tự");

        btnLietKe.setText("Liệt kê danh sách file");
        btnLietKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLietKeActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(listFile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(100, 100, 100)
                        .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPath, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnLietKe))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKytu)
                            .addComponent(jScrollPane1))))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPath))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKytu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLietKe)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLietKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLietKeActionPerformed
        // Lấy đường dẫn từ TextField
    File dir = new File(txtPath.getText());

    // Kiểm tra nếu đường dẫn là thư mục
    if (!dir.isDirectory()) { // Nếu không phải là thư mục
        JOptionPane.showMessageDialog(null, "Sai đường dẫn hoặc không phải thư mục!");
        return;
    }
    // Nếu là thư mục
    try {
        // Lấy danh sách file/thư mục trong thư mục
        File[] dsFile = dir.listFiles();

        if (dsFile != null) {
            // Tạo danh sách mô hình hiển thị
            DefaultListModel<String> dm = new DefaultListModel<>();

            // Lọc file/thư mục dựa trên từ khóa nhập vào
            String keyword = txtKytu.getText();
            for (File file : dsFile) {
                dm.addElement(file.getName()); // Thêm file/thư mục phù hợp vào danh sách

                //Chức năng nâng cao
              if (file.getName().contains(keyword)) {
                 dm.addElement(file.getName()); // Thêm file/thư mục phù hợp vào danh sách
              }
            }

            // Gắn mô hình vào JList để hiển thị
            listFile.setModel(dm);

            // Kiểm tra nếu không có kết quả
            if (dm.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Không có tập tin/thư mục nào phù hợp!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Không thể lấy danh sách tệp/thư mục!");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi: " + e.getMessage());
    }
    }//GEN-LAST:event_btnLietKeActionPerformed

    private void btnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPathActionPerformed
        this.fcpath.setVisible(true);

    // Thiết lập cho phép chọn tệp tin hay thư mục
    fcpath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

    // Cho hộp thoại hiển thị lên
    if (this.fcpath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        // Nếu nút Open được chọn
        try {
            txtPath.setText(fcpath.getSelectedFile().getCanonicalPath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    }//GEN-LAST:event_btnPathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBT02_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBT02_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBT02_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBT02_01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBT02_01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLietKe;
    private javax.swing.JButton btnPath;
    private javax.swing.JFileChooser fcpath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listFile;
    private javax.swing.JTextField txtKytu;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
