CREATE DATABASE QLSANXUAT
USE MASTER
USE QLSANXUAT
CREATE TABLE LOAI(
	MALOAI CHAR(5) PRIMARY KEY,
	TENLOAI NVARCHAR(20)
)
CREATE TABLE SANPHAM(
	MASP CHAR(5) PRIMARY KEY,
	TENSP NVARCHAR(100),
	MALOAI CHAR(5)
	FOREIGN KEY (MALOAI) REFERENCES LOAI(MALOAI)
	)

CREATE TABLE NHANVIEN(
	MANV CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(100),
	NGAYSINH DATE,
	PHAI BIT DEFAULT 1
)
CREATE TABLE PHIEUXUAT(
	MAPX INT IDENTITY(1,1) PRIMARY KEY,
	NGAYLAP DATE,
	MANV CHAR(5) FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
CREATE TABLE CTPX(
	MAPX INT,
	MASP CHAR(5),
	SL BIGINT,
	PRIMARY KEY(MAPX,MASP),
	FOREIGN KEY (MAPX) REFERENCES PHIEUXUAT(MAPX),
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
)

INSERT INTO LOAI VALUES 
('1',N'Vật Liệu Xây Dựng'),
('2',N'Hàng Tiêu Dùng'),
('3',N'Ngũ cốc')
INSERT INTO SANPHAM VALUES
('1',N'Xi Măng','1'),
('2',N'Gạch','1'),
('3',N'Gạo nàng hương','3'),
('4',N'Bột mì','3'),
('5',N'Kệ chén','2'),
('6',N'Đậu xanh','3')

INSERT INTO NHANVIEN VALUES
('NV01',N'Nguyễn Mai Thi','1982-5-15',0),
('NV02',N'Trần Đình Chiến','1980-12-2',1),
('NV03',N'Lê Thị Chi','1979-1-23',0)

INSERT INTO PHIEUXUAT (NGAYLAP,MANV) VALUES
('2010-3-12','NV01'),
('2010-2-3','NV02'),
('2010-6-1','NV03'),
('2010-6-16','NV01')

INSERT INTO CTPX (MAPX,MASP,SL)VALUES
(1,'1',10),
(1,'2',15),
(1,'3',5),
(2,'2',20),
(3,'1',20),
(3,'3',25),
(4,'5',12)

CREATE VIEW V1 AS
SELECT S.MASP,TENSP,SUM(SL)AS [TONGSOLUONG]
FROM PHIEUXUAT P INNER JOIN CTPX C ON P.MAPX = C.MAPX 
				INNER JOIN SANPHAM S ON S.MASP = c.MASP
WHERE YEAR(NGAYLAP) = 2010
GROUP BY S.MASP,TENSP
SELECT *
FROM V1
ORDER BY TENSP

CREATE VIEW V2 AS
SELECT S.MASP,TENSP,TENLOAI,NGAYLAP
FROM SANPHAM S INNER JOIN LOAI L ON S.MASP = L.MALOAI
				INNER JOIN CTPX C ON C.MASP = S.MASP
				INNER JOIN PHIEUXUAT P ON P.MAPX = C.MAPX
WHERE YEAR(NGAYLAP) = 2010 AND MONTH(NGAYLAP) BETWEEN 1 AND 6 AND DAY(NGAYLAP) BETWEEN 1 AND 31
SELECT *
FROM V2

CREATE VIEW V3 AS
SELECT L.MALOAI ,TENLOAI,COUNT(MASP) AS [SO LUONG SAN PHAM]
FROM SANPHAM S INNER JOIN LOAI L ON S.MALOAI = L.MALOAI
GROUP BY L.MALOAI, TENLOAI
SELECT *
FROM V3

CREATE VIEW V4 AS
SELECT COUNT(MAPX) AS [TONGSOLUONGPHIEUXUAT]
FROM PHIEUXUAT
WHERE MONTH(NGAYLAP) = 6 AND YEAR(NGAYLAP) = 2010
SELECT *
FROM V4

CREATE VIEW V5 AS
SELECT MAPX,NGAYLAP
FROM PHIEUXUAT
WHERE MANV LIKE 'NV01'
SELECT *
FROM V5

CREATE VIEW V6 AS
SELECT *
FROM NHANVIEN
WHERE DATEDIFF(YEAR,NGAYSINH,GETDATE()) > 25 AND DATEDIFF(YEAR,NGAYSINH,GETDATE()) < 30
INSERT INTO NHANVIEN VALUES ('NV04',N'Lê Thị Chi','1995-1-23',0)
SELECT *
FROM V6
DELETE FROM NHANVIEN
WHERE MANV LIKE 'NV04'

CREATE VIEW V7 AS
SELECT COUNT(MAPX) AS SOLUONGPHIEUXUAT,MANV
FROM PHIEUXUAT
GROUP BY MANV
SELECT *
FROM V7

CREATE VIEW V8 AS
SELECT SUM(SL) AS TONGSOLUONG, MASP
FROM CTPX
GROUP BY MASP
SELECT *
FROM V8	

CREATE VIEW V9 AS
SELECT TOP 1 COUNT(P.MAPX)AS SOLUONGPHIEXUAT, HOTEN
FROM PHIEUXUAT P INNER JOIN NHANVIEN N ON P.MANV = N.MANV
GROUP BY HOTEN
ORDER BY SOLUONGPHIEXUAT DESC
SELECT *
FROM V9

CREATE VIEW V10 AS
SELECT TOP 1 WITH TIES SUM(SL) AS SOLUONGXUAT,S.MASP,TENSP
FROM PHIEUXUAT P INNER JOIN CTPX C ON P.MAPX = C.MAPX
					INNER JOIN SANPHAM S ON C.MASP = S.MASP
WHERE YEAR(NGAYLAP) = 2010
GROUP BY TENSP,S.MASP,TENSP
ORDER BY SUM(SL) DESC
SELECT *
FROM V10	

CREATE FUNCTION F1(@TENSANPHAM NVARCHAR(100),@NAM INT)
RETURNS INT
AS
BEGIN
	DECLARE @SOLUONG INT
	IF NOT EXISTS (SELECT *
	FROM SANPHAM
	WHERE TENSP = @TENSANPHAM)
	BEGIN
	SET @SOLUONG = 0
	END
	ELSE
	BEGIN
	SET @SOLUONG =  ISNULL((SELECT SUM(SL)
	FROM CTPX C INNER JOIN SANPHAM S ON C.MASP = S.MASP
	INNER JOIN PHIEUXUAT P ON C.MAPX = P.MAPX
	WHERE TENSP LIKE @TENSANPHAM AND YEAR(NGAYLAP) = @NAM),0)
	END
	RETURN @SOLUONG
END

SELECT dbo.F1(N'Gạch',2010) AS SOLUONGXUATKHO

CREATE FUNCTION F2(@MANHANVIEN CHAR(5))
RETURNS INT
AS
BEGIN
	DECLARE @SOLUONG INT = 0
	IF NOT EXISTS(SELECT *
	FROM NHANVIEN
	WHERE MANV = @MANHANVIEN)
	BEGIN
	SET @SOLUONG =0
	END
	ELSE
	BEGIN
	SET @SOLUONG = ISNULL((SELECT COUNT(MAPX)
	FROM PHIEUXUAT
	WHERE MANV = @MANHANVIEN),0)
	END
	RETURN @SOLUONG
END

SELECT DBO.F2('KHONGTONTAI') AS SOLUONGPHIEUXUAT

CREATE FUNCTION F3(@NAM INT)
RETURNS TABLE
AS
	RETURN 
	(SELECT MASP
	FROM PHIEUXUAT P INNER JOIN CTPX C ON P.MAPX = C.MAPX
	WHERE YEAR(NGAYLAP) = 2010
	GROUP BY MASP)

SELECT * FROM DBO.F3(2010)

CREATE FUNCTION F4(@MANHANVIEN VARCHAR(5))
RETURNS TABLE
AS
	RETURN(
	SELECT *
	FROM PHIEUXUAT
	WHERE (@MANHANVIEN IS NULL OR MANV = @MANHANVIEN)
	)

SELECT *
FROM DBO.F4('NV01')

CREATE FUNCTION F5(@MAPHIEUXUAT INT)
RETURNS NVARCHAR(100)
AS
	BEGIN
	DECLARE @TENNHANVIEN NVARCHAR(100)
	SET @TENNHANVIEN = (SELECT HOTEN
	FROM PHIEUXUAT P INNER JOIN NHANVIEN N ON P.MANV = N.MANV
	WHERE P.MAPX = @MAPHIEUXUAT)
	RETURN @TENNHANVIEN
	END

SELECT DBO.F5(2) AS TENNHANVIEN

CREATE FUNCTION F6(@T1 DATE,@T2 DATE)
RETURNS TABLE
AS
RETURN (SELECT *
	FROM PHIEUXUAT
	WHERE @T1 <= @T2 AND NGAYLAP BETWEEN @T1 AND @T2)

SELECT *
FROM DBO.F6('2010-3-12','2010-6-3')

CREATE FUNCTION F7(@MAPHIEUXUAT INT)
RETURNS DATE
AS
BEGIN
	DECLARE @NGAYXUAT DATE
	SET @NGAYXUAT = (SELECT NGAYLAP
					FROM PHIEUXUAT
					WHERE MAPX = @MAPHIEUXUAT)
	RETURN @NGAYXUAT
END

SELECT DBO.F7(3) AS NGAYXUAT

CREATE PROCEDURE P1
@TENSANPHAM NVARCHAR(100)
AS
BEGIN
	DECLARE @SOLUONG INT
	SET @SOLUONG = (SELECT DBO.F1(@TENSANPHAM,2010))
	RETURN @SOLUONG
END

DECLARE @SOLUONG INT
EXEC @SOLUONG = P1 N'Gạo nàng hương'
SELECT @SOLUONG AS SOLUONG

CREATE PROCEDURE P2
@TENSANPHAM NVARCHAR(100)
AS
BEGIN
	DECLARE @SOLUONG INT
	IF NOT EXISTS (SELECT *
	FROM SANPHAM S INNER JOIN CTPX C ON S.MASP = C.MASP
	INNER JOIN PHIEUXUAT P ON P.MAPX = C.MAPX
	WHERE TENSP LIKE @TENSANPHAM)
	BEGIN
		SET @SOLUONG = 0
	END
	ELSE
	BEGIN
		SET @SOLUONG = ISNULL((SELECT SUM(SL)
		FROM SANPHAM S INNER JOIN CTPX C ON S.MASP = C.MASP
		INNER JOIN PHIEUXUAT P ON P.MAPX = C.MAPX
		WHERE TENSP LIKE @TENSANPHAM AND MONTH(NGAYLAP) BETWEEN 4 AND 6 AND YEAR(NGAYLAP) = 2010),0)
	END
	RETURN @SOLUONG
END

DECLARE @SOLUONG INT
EXEC  @SOLUONG = P2 N'Xi măng'
SELECT @SOLUONG AS SOLUONG

CREATE PROCEDURE P3
@TENSANPHAM NVARCHAR(100)
AS
BEGIN
	DECLARE @SOLUONG INT
	EXEC @SOLUONG = P2 @TENSANPHAM
	RETURN @SOLUONG
END

DECLARE @SOLUONG INT
EXEC  @SOLUONG = P3 N'Xi măng'
SELECT @SOLUONG AS SOLUONG

CREATE PROCEDURE P4
@MALOAI CHAR(5), @TENLOAI NVARCHAR(20)
AS
BEGIN
	INSERT INTO LOAI(MALOAI,TENLOAI) VALUES (@MALOAI,@TENLOAI)
END

EXEC P4 '4', N'Loại mới'
SELECT *
FROM LOAI

CREATE PROCEDURE P5
@MANHANVIEN CHAR(5)
AS
BEGIN
	DELETE FROM CTPX
	WHERE MAPX IN (SELECT MAPX
	FROM PHIEUXUAT
	WHERE MANV = @MANHANVIEN)
	DELETE FROM PHIEUXUAT
	WHERE MANV = @MANHANVIEN
	DELETE FROM NHANVIEN
	WHERE MANV = @MANHANVIEN
END

EXEC P5 'NV03'
SELECT *
FROM NHANVIEN

CREATE TRIGGER T1 ON CTPX
FOR INSERT
AS
BEGIN
	DECLARE @SLCHITIET INT
	SET @SLCHITIET = (SELECT COUNT(C.MAPX)
					FROM CTPX C INNER JOIN INSERTED I ON C.MAPX = I.MAPX)
	IF @SLCHITIET > 5
	BEGIN
		PRINT('KHONG NHAP QUA 5 CHI TIET CHO PHIEU XUAT NAY')
		ROLLBACK TRANSACTION
	END
END

INSERT INTO CTPX (MAPX,MASP,SL)VALUES
(1,'4',10)
INSERT INTO CTPX (MAPX,MASP,SL)VALUES
(1,'5',10)--toi day la phieu xuat thu 5
INSERT INTO CTPX (MAPX,MASP,SL)VALUES
(1,'6',10)

CREATE TRIGGER T2 ON PHIEUXUAT
FOR INSERT
AS
BEGIN
	DECLARE @SOPHIEU INT
	SET @SOPHIEU = (SELECT COUNT(*)
		FROM INSERTED I INNER JOIN PHIEUXUAT P ON I.MANV = P.MANV
		WHERE I.NGAYLAP = P.NGAYLAP)
	IF @SOPHIEU > 10
	BEGIN
		PRINT('BAN KHONG THE NHAP QUA 10 PHIEU TRONG 1 NGAY')
		ROLLBACK TRANSACTION
	END
END

INSERT INTO PHIEUXUAT (NGAYLAP,MANV) VALUES
('2010-3-12','NV02')
SELECT *
FROM PHIEUXUAT

CREATE TRIGGER T3 ON CTPX
INSTEAD OF INSERT
AS
BEGIN
	IF NOT EXISTS (SELECT *
	FROM INSERTED I INNER JOIN PHIEUXUAT P ON I.MAPX = P.MAPX)
	BEGIN
	PRINT('PHIEU XUAT NAY KHONG TON TAI')
	ROLLBACK TRANSACTION
	END
END

INSERT INTO CTPX (MAPX,MASP,SL)VALUES
(199,'1',10)


--
ALTER PROCEDURE P_LIETKEPHIEUXUAT
@X INT
AS
BEGIN 
DECLARE @MAPHIEUXUAT INT, @TENSANPHAM NVARCHAR(100), @SOLUONG BIGINT, @NGAY DATE,@ROW INT
DECLARE C_LIETKEPHIEUXUAT CURSOR FOR
	SELECT DISTINCT NGAYLAP,P.MAPX,TENSP,SL
FROM PHIEUXUAT P INNER JOIN CTPX C ON P.MAPX=C.MAPX
				INNER JOIN SANPHAM S ON S.MASP = C.MASP
				WHERE MONTH(NGAYLAP) = @X
				GROUP BY P.MAPX,TENSP,SL,NGAYLAP
OPEN C_LIETKEPHIEUXUAT
FETCH NEXT FROM C_LIETKEPHIEUXUAT INTO @NGAY,@MAPHIEUXUAT, @TENSANPHAM,@SOLUONG
SET @ROW =1
WHILE @@FETCH_STATUS = 0
BEGIN
PRINT N'Ngày' + CONVERT(VARCHAR(20),@NGAY) + CHAR(13) + CHAR(10)+ N'Phiếu số' + CONVERT(VARCHAR(5),@MAPHIEUXUAT) + N':' + @TENSANPHAM + N'-Số lượng:'+ CONVERT(VARCHAR(20),@SOLUONG)
FETCH NEXT FROM C_LIETKEPHIEUXUAT INTO @NGAY,@MAPHIEUXUAT, @TENSANPHAM,@SOLUONG
SET @ROW = @ROW + 1
END
CLOSE C_LIETKEPHIEUXUAT
DEALLOCATE C_LIETKEPHIEUXUAT
END

EXEC P_LIETKEPHIEUXUAT 6