CREATE DATABASE QLSANXUAT
USE MASTER
USE QLSANXUAT
CREATE TABLE LOAI(
	MALOAI CHAR(5) PRIMARY KEY,
	TENLOAI NVARCHAR(20)
)
CREATE TABLE SANPHAM(
	MASP CHAR(5) PRIMARY KEY,
	TENSP NVARCHAR(100),
	MALOAI CHAR(5)
	FOREIGN KEY (MALOAI) REFERENCES LOAI(MALOAI)
	)

CREATE TABLE NHANVIEN(
	MANV CHAR(5) PRIMARY KEY,
	HOTEN NVARCHAR(100),
	NGAYSINH DATE,
	PHAI BIT DEFAULT 1
)
CREATE TABLE PHIEUXUAT(
	MAPX INT IDENTITY(1,1) PRIMARY KEY,
	NGAYLAP DATE,
	MANV CHAR(5) FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
)
CREATE TABLE CTPX(
	MAPX INT,
	MASP CHAR(5),
	SL BIGINT,
	PRIMARY KEY(MAPX,MASP),
	FOREIGN KEY (MAPX) REFERENCES PHIEUXUAT(MAPX),
	FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
)

INSERT INTO LOAI VALUES 
('1',N'Vật Liệu Xây Dựng'),
('2',N'Hàng Tiêu Dùng'),
('3',N'Ngũ cốc')
INSERT INTO SANPHAM VALUES
('1',N'Xi Măng','1'),
('2',N'Gạch','1'),
('3',N'Gạo nàng hương','3'),
('4',N'Bột mì','3'),
('5',N'Kệ chén','2'),
('6',N'Đậu xanh','3')

INSERT INTO NHANVIEN VALUES
('NV01',N'Nguyễn Mai Thi','1982-5-15',0),
('NV02',N'Trần Đình Chiến','1980-12-2',1),
('NV03',N'Lê Thị Chi','1979-1-23',0)

INSERT INTO PHIEUXUAT (NGAYLAP,MANV) VALUES
('2010-3-12','NV01'),
('2010-2-3','NV02'),
('2010-6-1','NV03'),
('2010-6-16','NV01')

INSERT INTO CTPX (MAPX,MASP,SL)VALUES
(1,'1',10),
(1,'2',15),
(1,'3',5),
(2,'2',20),
(3,'1',20),
(3,'3',25),
(4,'5',12)

CREATE VIEW V1 AS
SELECT S.MASP,TENSP,SUM(SL)AS [TONGSOLUONG]
FROM PHIEUXUAT P INNER JOIN CTPX C ON P.MAPX = C.MAPX 
				INNER JOIN SANPHAM S ON S.MASP = c.MASP
WHERE YEAR(NGAYLAP) = 2010
GROUP BY S.MASP,TENSP
SELECT *
FROM V1
ORDER BY TENSP

CREATE VIEW V2 AS
SELECT S.MASP,TENSP,TENLOAI,NGAYLAP
FROM SANPHAM S INNER JOIN LOAI L ON S.MASP = L.MALOAI
				INNER JOIN CTPX C ON C.MASP = S.MASP
				INNER JOIN PHIEUXUAT P ON P.MAPX = C.MAPX
WHERE YEAR(NGAYLAP) = 2010 AND MONTH(NGAYLAP) BETWEEN 1 AND 6 AND DAY(NGAYLAP) BETWEEN 1 AND 31
SELECT *
FROM V2

CREATE VIEW V3 AS
SELECT L.MALOAI ,TENLOAI,COUNT(MASP) AS [SO LUONG SAN PHAM]
FROM SANPHAM S INNER JOIN LOAI L ON S.MALOAI = L.MALOAI
GROUP BY L.MALOAI, TENLOAI
SELECT *
FROM V3

CREATE VIEW V4 AS
SELECT COUNT(MAPX) AS [TONGSOLUONGPHIEUXUAT]
FROM PHIEUXUAT
WHERE MONTH(NGAYLAP) = 6 AND YEAR(NGAYLAP) = 2010
SELECT *
FROM V4

CREATE VIEW V5 AS
SELECT MAPX,NGAYLAP
FROM PHIEUXUAT
WHERE MANV LIKE 'NV01'
SELECT *
FROM V5

CREATE VIEW V6 AS
SELECT *
FROM NHANVIEN
WHERE DATEDIFF(YEAR,NGAYSINH,GETDATE()) > 25 AND DATEDIFF(YEAR,NGAYSINH,GETDATE()) < 30
INSERT INTO NHANVIEN VALUES ('NV04',N'Lê Thị Chi','1995-1-23',0)
SELECT *
FROM V6
DELETE FROM NHANVIEN
WHERE MANV LIKE 'NV04'

CREATE VIEW V7 AS
SELECT COUNT(MAPX) AS SOLUONGPHIEUXUAT,MANV
FROM PHIEUXUAT
GROUP BY MANV
SELECT *
FROM V7

CREATE VIEW V8 AS
SELECT SUM(SL) AS TONGSOLUONG, MASP
FROM CTPX
GROUP BY MASP
SELECT *
FROM V8	

CREATE VIEW V9 AS
SELECT TOP 1 COUNT(P.MAPX)AS SOLUONGPHIEXUAT, HOTEN
FROM PHIEUXUAT P INNER JOIN NHANVIEN N ON P.MANV = N.MANV
GROUP BY HOTEN
ORDER BY SOLUONGPHIEXUAT DESC
SELECT *
FROM V9

CREATE VIEW V10 AS
SELECT TOP 1 WITH TIES SUM(SL) AS SOLUONGXUAT,S.MASP,TENSP
FROM PHIEUXUAT P INNER JOIN CTPX C ON P.MAPX = C.MAPX
					INNER JOIN SANPHAM S ON C.MASP = S.MASP
WHERE YEAR(NGAYLAP) = 2010
GROUP BY TENSP,S.MASP,TENSP
ORDER BY SUM(SL) DESC
SELECT *
FROM V10	