/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bt02_02;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class frmBT02_02 extends javax.swing.JFrame {

    /**
     * Creates new form frmBT02_02
     */
    public frmBT02_02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fcpath = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFileName = new javax.swing.JTextField();
        txtNhapChuoi = new javax.swing.JTextField();
        txtNoiDungFile = new javax.swing.JTextField();
        btnPath = new javax.swing.JButton();
        btnInputStream = new javax.swing.JButton();
        btnOutputStream = new javax.swing.JButton();
        btnReader = new javax.swing.JButton();
        btnWriter = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nhập tên tập tin:");

        jLabel2.setText("Nhập chuỗi");

        jLabel3.setText("Nội dung file");

        txtNoiDungFile.setEditable(false);

        btnPath.setText("Chọn tập tin");
        btnPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPathActionPerformed(evt);
            }
        });

        btnInputStream.setText("Đọc file nhị phân");
        btnInputStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputStreamActionPerformed(evt);
            }
        });

        btnOutputStream.setText("Ghi file nhị phân");
        btnOutputStream.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutputStreamActionPerformed(evt);
            }
        });

        btnReader.setText("Đọc file văn bản");
        btnReader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaderActionPerformed(evt);
            }
        });

        btnWriter.setText("Ghi file văn bản");
        btnWriter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWriterActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNhapChuoi)
                            .addComponent(txtNoiDungFile)
                            .addComponent(txtFileName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPath)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnReader, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInputStream, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOutputStream, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(btnWriter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnThoat)
                        .addContainerGap(30, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtFileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnPath)))
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2))
                    .addComponent(txtNhapChuoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtNoiDungFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInputStream)
                    .addComponent(btnOutputStream))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReader)
                    .addComponent(btnWriter)
                    .addComponent(btnThoat))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOutputStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutputStreamActionPerformed
        // TODO add your handling code here:
        byte a[] = new byte[20];
        File file;
        int i;
        char s[] = txtNhapChuoi.getText().toCharArray();
        for (i = 0; i < s.length; i++)
        {
            a[i] = (byte)s[i];
        }
        try {
            file = new File(txtFileName.getText());
            FileOutputStream fo = new FileOutputStream(file);
            fo.write(a);
            fo.close();
            } catch (IOException e) {e.printStackTrace();}
    }//GEN-LAST:event_btnOutputStreamActionPerformed

    private void btnInputStreamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputStreamActionPerformed
        // TODO add your handling code here:
        byte a[];
        File file;
        try {
            file = new File(txtFileName.getText());
            FileInputStream fi = new FileInputStream(file);
            a = new byte[fi.available()];
            fi.read(a);
            fi.close();
            txtNoiDungFile.setText(new String(a));
            } catch (Exception e) {}
    }//GEN-LAST:event_btnInputStreamActionPerformed

    private void btnWriterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriterActionPerformed
        // TODO add your handling code here:
        try{
            FileWriter fw = new FileWriter(new File(txtFileName.getText()));
            fw.write(txtNhapChuoi.getText());
            fw.close();    
        }catch(Exception e) {e.printStackTrace();}
    }//GEN-LAST:event_btnWriterActionPerformed

    private void btnReaderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaderActionPerformed
        // TODO add your handling code here:
        try{
            FileReader fr = new FileReader(new File(txtFileName.getText()));
            StringBuffer sb = new StringBuffer();
            char ca[] = new char[5];
            while(fr.ready())
            {
                int len = fr.read(ca);
                sb.append(ca,0,len);
            }
            fr.close();
            txtNoiDungFile.setText(sb+"");
        }catch (Exception e){
            e.printStackTrace();
        }   
    }//GEN-LAST:event_btnReaderActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPathActionPerformed
        // TODO add your handling code here:
        this.fcpath.setVisible(true);

    // Thiết lập cho phép chọn tệp tin hay thư mục
    fcpath.setFileSelectionMode(JFileChooser.FILES_ONLY);

    // Cho hộp thoại hiển thị lên
    if (this.fcpath.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
        // Nếu nút Open được chọn
        try {
            txtFileName.setText(fcpath.getSelectedFile().getCanonicalPath());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    }//GEN-LAST:event_btnPathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBT02_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBT02_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBT02_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBT02_02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBT02_02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInputStream;
    private javax.swing.JButton btnOutputStream;
    private javax.swing.JButton btnPath;
    private javax.swing.JButton btnReader;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnWriter;
    private javax.swing.JFileChooser fcpath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtNhapChuoi;
    private javax.swing.JTextField txtNoiDungFile;
    // End of variables declaration//GEN-END:variables
}
