// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLySinhVien.DAL.Models;

#nullable disable

namespace QuanLySinhVien.DAL.Migrations
{
    [DbContext(typeof(QuanLySinhVienDbContext))]
    [Migration("20260729143436_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLySinhVien.DAL.Models.ChuyenNganh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KhoaId")
                        .HasColumnType("int");

                    b.Property<string>("TenChuyenNganh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KhoaId");

                    b.ToTable("ChuyenNganhs");
                });

            modelBuilder.Entity("QuanLySinhVien.DAL.Models.Khoa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NamThanhLap")
                        .HasColumnType("int");

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TongSoGiangVien")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Khoas");
                });

            modelBuilder.Entity("QuanLySinhVien.DAL.Models.SinhVien", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChuyenNganhId")
                        .HasColumnType("int");

                    b.Property<double?>("DiemTB")
                        .HasColumnType("float");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChuyenNganhId");

                    b.ToTable("SinhViens");
                });

            modelBuilder.Entity("QuanLySinhVien.DAL.Models.ChuyenNganh", b =>
                {
                    b.HasOne("QuanLySinhVien.DAL.Models.Khoa", "Khoa")
                        .WithMany("ChuyenNganhs")
                        .HasForeignKey("KhoaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("QuanLySinhVien.DAL.Models.SinhVien", b =>
                {
                    b.HasOne("QuanLySinhVien.DAL.Models.ChuyenNganh", "ChuyenNganh")
                        .WithMany("SinhViens")
                        .HasForeignKey("ChuyenNganhId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChuyenNganh");
                });

            modelBuilder.Entity("QuanLySinhVien.DAL.Models.ChuyenNganh", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("QuanLySinhVien.DAL.Models.Khoa", b =>
                {
                    b.Navigation("ChuyenNganhs");
                });
#pragma warning restore 612, 618
        }
    }
}
