/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bt02_04;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author HP
 */
public class frmBT02_04 extends javax.swing.JFrame {
    private JFileChooser fcpath = new JFileChooser();

    /**
     * Creates new form frm02_04
     */
    public frmBT02_04() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFileNguon = new javax.swing.JTextField();
        txtFileDich = new javax.swing.JTextField();
        btnChonNguon = new javax.swing.JButton();
        btnCopy = new javax.swing.JButton();
        btnChonDich = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tập tin nguồn");

        jLabel2.setText("Tập tin đích");

        txtFileNguon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFileNguonActionPerformed(evt);
            }
        });

        btnChonNguon.setText("Chọn đường dẫn");
        btnChonNguon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonNguonActionPerformed(evt);
            }
        });

        btnCopy.setText("Copy");
        btnCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyActionPerformed(evt);
            }
        });

        btnChonDich.setText("Chọn đường dẫn");
        btnChonDich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonDichActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFileNguon, javax.swing.GroupLayout.DEFAULT_SIZE, 353, Short.MAX_VALUE)
                    .addComponent(txtFileDich))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCopy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChonNguon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChonDich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFileNguon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChonNguon)))
                .addGap(37, 37, 37)
                .addComponent(btnCopy)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFileDich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChonDich)))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFileNguonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFileNguonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFileNguonActionPerformed

    private void btnChonNguonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonNguonActionPerformed
        // TODO add your handling code here:
        fcpath.setFileSelectionMode(JFileChooser.FILES_ONLY);

    if (fcpath.showOpenDialog(this)
            == JFileChooser.APPROVE_OPTION) {

        try {

            txtFileNguon.setText(
                    fcpath.getSelectedFile()
                            .getCanonicalPath()
            );

        } catch (IOException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Lỗi: " + e.getMessage()
            );
        }
    }
    }//GEN-LAST:event_btnChonNguonActionPerformed

    private void btnChonDichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonDichActionPerformed
        // TODO add your handling code here:
        fcpath.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

    if (fcpath.showOpenDialog(this)
            == JFileChooser.APPROVE_OPTION) {

        try {

            txtFileDich.setText(
                    fcpath.getSelectedFile()
                            .getCanonicalPath()
            );

        } catch (IOException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Lỗi: " + e.getMessage()
            );
        }
    }
    }//GEN-LAST:event_btnChonDichActionPerformed

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyActionPerformed
        // TODO add your handling code here:
        String fileNguon = txtFileNguon.getText();
    String fileDich = txtFileDich.getText();

    if (fileNguon.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Vui lòng chọn tập tin nguồn!"
        );

        return;
    }

    if (fileDich.isEmpty()) {

        JOptionPane.showMessageDialog(
                this,
                "Vui lòng chọn thư mục đích!"
        );

        return;
    }

    try {

        File fileInput = new File(fileNguon);

        if (!fileInput.exists()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Tập tin nguồn không tồn tại!"
            );

            return;
        }

        File fileOutput =
                new File(fileDich, "Mang.txt");

        Scanner sc =
                new Scanner(fileInput);

        FileWriter fw =
                new FileWriter(fileOutput);

        int[] mang = new int[100];

        int soPhanTu = 0;

        while (sc.hasNextInt()) {

            mang[soPhanTu] =
                    sc.nextInt();

            soPhanTu++;

            // Đủ 100 phần tử
            if (soPhanTu == 100) {

                for (int i = 0; i < soPhanTu; i++) {

                    fw.write(
                            mang[i] + " "
                    );
                }

                fw.write("\n");

                soPhanTu = 0;
            }
        }

        // Ghi phần còn lại nếu < 100
        if (soPhanTu > 0) {

            for (int i = 0; i < soPhanTu; i++) {

                fw.write(
                        mang[i] + " "
                );
            }

            fw.write("\n");
        }

        sc.close();
        fw.close();

        JOptionPane.showMessageDialog(
                this,
                "Đã tách tập tin và ghi vào:\n"
                + fileOutput.getAbsolutePath()
        );

    } catch (IOException e) {

        JOptionPane.showMessageDialog(
                this,
                "Lỗi xử lý file: "
                + e.getMessage()
        );
    }
    }//GEN-LAST:event_btnCopyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmBT02_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmBT02_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmBT02_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmBT02_04.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBT02_04().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonDich;
    private javax.swing.JButton btnChonNguon;
    private javax.swing.JButton btnCopy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtFileDich;
    private javax.swing.JTextField txtFileNguon;
    // End of variables declaration//GEN-END:variables
}
