/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bt05_06;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.Socket;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class FTPClient extends javax.swing.JFrame {

    private Socket socket;

    private DataInputStream dis;
    private DataOutputStream dos;

    private String path = "";

    public static final int PORT = 10000;

    /**
     * Creates new form FTPClient
     */
    public FTPClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fchPath = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        txtDomain = new javax.swing.JTextField();
        btnUp = new javax.swing.JButton();
        btnDownload = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnBrowse = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstClientPath = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPath = new javax.swing.JList<>();
        txtPass = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Domain");

        txtDomain.setText("localhost");

        btnUp.setText("Up");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });

        jLabel2.setText("user");

        jLabel3.setText("pass");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jLabel4.setText("Client's Folder");

        jLabel5.setText("Server Folder");

        jScrollPane1.setViewportView(lstClientPath);

        jScrollPane2.setViewportView(lstPath);

        txtPass.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDomain)
                        .addGap(18, 18, 18)
                        .addComponent(btnUp)
                        .addGap(59, 59, 59)
                        .addComponent(btnDownload)
                        .addGap(60, 60, 60))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser)
                            .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLogin)
                            .addComponent(btnBrowse))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4)
                        .addGap(131, 131, 131)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDomain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUp)
                            .addComponent(btnDownload))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLogin))))
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBrowse))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String domain = txtDomain.getText().trim();
        String user = txtUser.getText().trim();
        String pass = txtPass.getText().trim();

        if (domain.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng nhập Domain!"
            );
            return;
        }

        if (user.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng nhập User!"
            );
            return;
        }

        if (pass.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng nhập Password!"
            );
            return;
        }

        try {

            // Tạo Socket kết nối Server
            socket = new Socket(domain, PORT);

            // Tạo luồng nhận dữ liệu
            dis = new DataInputStream(
                    socket.getInputStream()
            );

            // Tạo luồng gửi dữ liệu
            dos = new DataOutputStream(
                    socket.getOutputStream()
            );

            // Gửi lệnh đăng nhập
            dos.writeUTF("DANGNHAP");

            // Gửi username
            dos.writeUTF(user);

            // Gửi password
            dos.writeUTF(pass);

            dos.flush();

            // Nhận kết quả đăng nhập
            int result = dis.readInt();

            String message = dis.readUTF();

            if (result == 1) {

                JOptionPane.showMessageDialog(
                        this,
                        "Đăng nhập thành công!"
                );

                // Nhận danh sách file Server
                nhanDanhSachServer();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        message
                );

                socket.close();
                socket = null;
                dis = null;
                dos = null;
            }

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "Không thể kết nối Server:\n"
                    + ex.getMessage()
            );
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();

        chooser.setFileSelectionMode(
                JFileChooser.DIRECTORIES_ONLY
        );

        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            try {

                File selectedFolder
                        = chooser.getSelectedFile();

                path
                        = selectedFolder.getCanonicalPath();

                hienThiFileClient();

            } catch (IOException ex) {

                JOptionPane.showMessageDialog(
                        this,
                        "Không thể đọc thư mục:\n"
                        + ex.getMessage()
                );
            }
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        // TODO add your handling code here:
        if (socket == null || dos == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bạn chưa đăng nhập Server!"
            );

            return;
        }

        if (path.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn Client Folder!"
            );

            return;
        }

        String fileName
                = lstClientPath.getSelectedValue();

        if (fileName == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn file cần Upload!"
            );

            return;
        }

        File file
                = new File(path, fileName);

        if (!file.exists()) {

            JOptionPane.showMessageDialog(
                    this,
                    "File không tồn tại!"
            );

            return;
        }

        try {

            System.out.println(
                    "Đang Upload: "
                    + file.getAbsolutePath()
            );

            // Gửi lệnh UPLOAD
            dos.writeUTF("UPLOAD");

            // Gửi tên file
            dos.writeUTF(fileName);

            // Gửi kích thước file
            dos.writeLong(file.length());

            // Gửi nội dung file
            try (FileInputStream fis
                    = new FileInputStream(file)) {

                byte[] buffer = new byte[4096];

                int read;

                while ((read = fis.read(buffer)) != -1) {

                    dos.write(
                            buffer,
                            0,
                            read
                    );
                }
            }

            dos.flush();

            System.out.println(
                    "Đã gửi file lên Server."
            );

            // Nhận kết quả từ Server
            int result = dis.readInt();

            String message = dis.readUTF();

            if (result == 1) {

                JOptionPane.showMessageDialog(
                        this,
                        "Đã Upload file thành công!"
                );

                // Server gửi lại danh sách file mới
                nhanDanhSachServer();

            } else {

                JOptionPane.showMessageDialog(
                        this,
                        message
                );
            }

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "Upload thất bại:\n"
                    + ex.getMessage()
            );
        }
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        // TODO add your handling code here:
        if (socket == null || dos == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Bạn chưa đăng nhập Server!"
            );

            return;
        }

        if (path.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng Browse đến Client Folder trước!"
            );

            return;
        }

        String fileName
                = lstPath.getSelectedValue();

        if (fileName == null) {

            JOptionPane.showMessageDialog(
                    this,
                    "Vui lòng chọn file ở Server Folder!"
            );

            return;
        }

        try {

            System.out.println(
                    "Đang Download: "
                    + fileName
            );

            // Gửi lệnh DOWNLOAD
            dos.writeUTF("DOWNLOAD");

            // Gửi tên file
            dos.writeUTF(fileName);

            dos.flush();

            // Nhận kết quả
            int result = dis.readInt();

            if (result == 0) {

                String message
                        = dis.readUTF();

                JOptionPane.showMessageDialog(
                        this,
                        message
                );

                return;
            }

            // Nhận kích thước file
            long fileSize
                    = dis.readLong();

            File outputFile
                    = new File(path, fileName);

            // Nhận dữ liệu file
            try (FileOutputStream fos
                    = new FileOutputStream(outputFile)) {

                byte[] buffer
                        = new byte[4096];

                long remaining = fileSize;

                while (remaining > 0) {

                    int read
                            = dis.read(
                                    buffer,
                                    0,
                                    (int) Math.min(
                                            buffer.length,
                                            remaining
                                    )
                            );

                    if (read == -1) {

                        throw new IOException(
                                "Server ngắt kết nối!"
                        );
                    }

                    fos.write(
                            buffer,
                            0,
                            read
                    );

                    remaining -= read;
                }
            }

            JOptionPane.showMessageDialog(
                    this,
                    "Download thành công!"
            );

            // Cập nhật Client Folder
            hienThiFileClient();

            System.out.println(
                    "Download hoàn tất."
            );

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "Download thất bại:\n"
                    + ex.getMessage()
            );
        }
    }//GEN-LAST:event_btnDownloadActionPerformed

    private void nhanDanhSachServer() {

        try {

            int n = dis.readInt();

            DefaultListModel<String> model
                    = new DefaultListModel<>();

            for (int i = 0; i < n; i++) {

                String fileName = dis.readUTF();

                model.addElement(fileName);
            }

            lstPath.setModel(model);

        } catch (IOException ex) {

            JOptionPane.showMessageDialog(
                    this,
                    "Lỗi nhận danh sách Server:\n"
                    + ex.getMessage()
            );
        }
    }

    private void hienThiFileClient() {

        if (path.isEmpty()) {
            return;
        }

        File folder = new File(path);

        File[] files = folder.listFiles();

        DefaultListModel<String> model
                = new DefaultListModel<>();

        if (files != null) {

            for (File file : files) {

                if (file.isFile()) {

                    model.addElement(
                            file.getName()
                    );
                }
            }
        }

        lstClientPath.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTPClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTPClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTPClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTPClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTPClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnUp;
    private javax.swing.JFileChooser fchPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstClientPath;
    private javax.swing.JList<String> lstPath;
    private javax.swing.JTextField txtDomain;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
